import { Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'


const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Uber-Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={montserrat.className}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
